export const ProposalTypeIndex = {
  SELLPROPERTY: 0,
  BUYPROPERTY: 1,
  USESAFETY: 2,
  USEREINVESTMENT: 3,
  REVENUETHRESHOLDCHANGE: 4,
  CHALLENGEAUTHORITY: 5,
  REMOVEAUTHORITY: 6,
  PROPOSEREMOVEPROPOSAL: 7,
} as const;